import test from 'node:test';
import assert from 'node:assert/strict';
import {exactSelectedIds,selectedReview,prepareSelectedIncoming,selectedViewFilters} from './selectedIncomingWorkflow.js';
const context=(decisions=[])=>({candidate_scope_revision:'scope-0',draft:{draft_version:0,selection_mode:'all',decisions,decisions_total:decisions.length,decisions_truncated:false}});
const counts=count=>({preview_sha256:'preview',expected_binding_version:4,expected_query_revision:'query',selected_epoch_count:count,accepted_epoch_count:count,already_present_epoch_count:0,retained_epoch_count:100,next_epoch_count:100+count,accepted_cell_count:1});
function server(initial){let current=initial;const calls=[];return {calls,get current(){return current;},request:async(path,options)=>{calls.push({path,...options});if(path.endsWith('/draft')){assert.equal(options.body.expected_version,current.draft.draft_version);assert.equal(options.body.expected_candidate_scope_revision,current.candidate_scope_revision);const decisions=new Map(current.draft.decisions.map(v=>[v.epoch_uuid,v]));for(const value of options.body.decisions)decisions.set(value.epoch_uuid,{selected:false,reviewed:false,excluded:false,...decisions.get(value.epoch_uuid),...value});current={...current,candidate_scope_revision:`scope-${current.draft.draft_version+1}`,draft:{...current.draft,draft_version:current.draft.draft_version+1,selection_mode:options.body.selection_mode,decisions:[...decisions.values()],decisions_total:decisions.size}};return current;}assert.ok(path.endsWith('/preview'));assert.equal(options.body.mode,'selected');assert.equal(options.body.expected_draft_version,current.draft.draft_version);assert.equal(options.body.expected_candidate_scope_revision,current.candidate_scope_revision);return counts(current.draft.decisions.filter(v=>v.selected&&v.reviewed&&!v.excluded).length);}};}
test('selection has no focused-row fallback and rejects duplicates and unavailable IDs',()=>{for(const ids of [[],null,['a','a'],[null]])assert.throws(()=>exactSelectedIds(ids));assert.deepEqual(exactSelectedIds(['a']),['a']);assert.ok(Object.isFrozen(exactSelectedIds(['a'])));});
test('review is explicit and excluded selection fails before any save or preview',async()=>{const s=server(context([{epoch_uuid:'excluded',excluded:true}]));await assert.rejects(prepareSelectedIncoming({root:'/c',context:s.current,ids:['a']},s.request),/Review the selected/);await assert.rejects(prepareSelectedIncoming({root:'/c',context:s.current,ids:['excluded'],review:true},s.request),/excluded/);assert.deepEqual(s.calls,[]);});
test('complete actor draft is required; missing or truncated decisions cannot imply reviewed or zero',()=>{for(const draft of [{draft_version:1},{...context().draft,decisions_truncated:true},{...context().draft,decisions_total:1}])assert.throws(()=>selectedReview({draft},['a']),/complete review draft/);});
test('explicit review replaces selected membership only, retains other reviews/exclusions, and never accepts',async()=>{const s=server(context([{epoch_uuid:'prior',selected:true,reviewed:true,excluded:true},{epoch_uuid:'keep',selected:false,reviewed:true,excluded:false}]));const preview=await prepareSelectedIncoming({root:'/c',context:s.current,ids:['a','b'],review:true},s.request);assert.equal(preview.selected_epoch_count,2);assert.deepEqual(s.current.draft.decisions.find(v=>v.epoch_uuid==='prior'),{epoch_uuid:'prior',selected:false,reviewed:true,excluded:true});assert.deepEqual(s.current.draft.decisions.find(v=>v.epoch_uuid==='keep'),{epoch_uuid:'keep',selected:false,reviewed:true,excluded:false});assert.deepEqual(s.calls.map(v=>v.path),['/c/draft','/c/preview']);assert.ok(s.calls[0].body.decisions.every(v=>!Object.hasOwn(v,'excluded')));});
test('already reviewed intent writes no review flags and uses the refreshed save fences',async()=>{const s=server(context([{epoch_uuid:'a',selected:false,reviewed:true,excluded:false}]));await prepareSelectedIncoming({root:'/c',context:s.current,ids:['a']},s.request);assert.deepEqual(s.calls[0].body.decisions,[{epoch_uuid:'a',selected:true}]);assert.equal(s.calls[1].body.expected_draft_version,1);});
test('multi-page intent batches exact flags and failure is never replayed or previewed',async()=>{const ids=Array.from({length:501},(_,i)=>`id-${i}`),s=server(context());let calls=0;await assert.rejects(prepareSelectedIncoming({root:'/c',context:s.current,ids,review:true},async(...args)=>{if(++calls===2)throw Error('reply lost');return s.request(...args);}),/reply lost/);assert.equal(calls,2);assert.equal(s.calls.length,1);assert.equal(s.current.draft.decisions.length,250);});
test('a fresh preview cannot silently omit one selected epoch',async()=>{const s=server(context());await assert.rejects(prepareSelectedIncoming({root:'/c',context:s.current,ids:['a','b'],review:true},async(path,opts)=>path.endsWith('/preview')?counts(1):s.request(path,opts)),/every selected epoch/);});
test('View selected keeps all 1000 exact identities in bounded clauses and preserves existing filters',()=>{const ids=Array.from({length:1000},(_,i)=>`00000000-0000-0000-0000-${String(i).padStart(12,'0')}`),original={cell_type:'ON',metadata_predicate:JSON.stringify({field:'date',operator:'eq',value:'2026-10-01'})};const result=selectedViewFilters(original,ids),predicate=JSON.parse(result.metadata_predicate);assert.equal(result.cell_type,'ON');assert.deepEqual(predicate.all[0],JSON.parse(original.metadata_predicate));assert.deepEqual(predicate.all[1].any.flatMap(v=>v.value),ids);assert.ok(predicate.all[1].any.every(v=>JSON.stringify(v.value).length<4096));assert.ok(!original.metadata_predicate.includes('epoch'));});

test('large selection identities have no user cardinality ceiling',()=>{const ids=Array.from({length:20000},(_,i)=>String(i));assert.deepEqual(exactSelectedIds(ids),ids);});

test('disk checkpoint omits oversized Workbench selections but preserves live UUIDs and every recovery field',async()=>{
 const {compactWorkbenchSelections}=await import('./selectedIncomingWorkflow.js');
 const ids=Array.from({length:100000},(_,i)=>`00000000-0000-0000-0000-${String(i).padStart(12,'0')}`),recovery={selected:ids,operation:'op',preview:{preview_sha256:'sealed'},unconfirmed:true,acceptPending:true,receipt:{event_uuid:'event'},exportState:{acceptOperation:'export-op',prepared:{token:'export'}},viewer:{focused:'epoch'}};
 const protocol={workbench:{active:'candidate',drafts:{candidate:recovery},cumulative:{prepared:{candidate_revision_uuid:'union'},drafts:{union:recovery}}}};
 const checkpoint={sessions:[['route',protocol]],protocolSessions:[['protocol',protocol]],sourceMerge:{operation:'separate'},unrelated:{selected:ids}};
 const result=compactWorkbenchSelections(checkpoint);
 assert.equal(protocol.workbench.drafts.candidate.selected,ids);assert.equal(ids.length,100000);assert.equal(result.unrelated,checkpoint.unrelated);assert.equal(result.sourceMerge,checkpoint.sourceMerge);
 for(const value of [result.sessions[0][1],result.protocolSessions[0][1]])for(const draft of [value.workbench.drafts.candidate,value.workbench.cumulative.drafts.union]){assert.deepEqual(draft,{...recovery,selected:[],selection_omitted_count:100000});}
 assert.ok(JSON.stringify({...result,unrelated:null}).length<2*1024*1024);
 assert.equal(compactWorkbenchSelections({sessions:[['s',{workbench:{drafts:{c:{selected:['one']}}}}]]}).sessions[0][1].workbench.drafts.c.selected[0],'one');
});
