import {useCallback,useEffect,useRef,useState} from 'react';
import {Activity,GitBranch,Info,Layers3,RefreshCw} from 'lucide-react';
import {humanize,number,time} from '../../api.js';
import {activeProtocolSuggestions} from "../../protocol-overview/protocolSuggestions.js";
import {reviewKey,reviewWorklist} from '../incomingReview.js';
import IncomingExportDialog from "../../exports/ui/IncomingExportDialog.jsx";
import WorkbenchExportDialog from "../../exports/ui/WorkbenchExportDialog.jsx";
import {nextWorkbenchWorkflow} from "../../exports/workbenchExport.js";
import MetadataExplorer from '../../metadata-explorer/ui/MetadataExplorer.jsx';
import FrozenIncomingReview from './FrozenIncomingReview.jsx';
import CumulativeIncomingReview from './CumulativeIncomingReview.jsx';
import useWorkbenchQueue from '../useWorkbenchQueue.js';
import useIncomingMergeIntent from '../useIncomingMergeIntent.js';
import './IncomingWorkbench.css';

export default function IncomingWorkbench({projectId,protocolId,protocols=[],suggestions=[],loading=false,error,onRetry,onChange,onApplied,onQC,onInspect,revision,session,onSession,initialCandidateId=null,initialExportIntent=null,initialAcceptOperation=null,authority=undefined,filterTarget=null,toolbarTarget=null,initialMergeIntent=null,onClaimMergeIntent}){
  const queue=useWorkbenchQueue(protocolId,revision,authority);
  const cumulative=queue.data?.contract_version===1;
  const preparedSupported=queue.data?.capabilities?.cumulative_pending_browse===true;
  const saved=useRef(session||{}).current;
  const [selected,setSelected]=useState(saved.selected||[]),[active,setActive]=useState(initialCandidateId||saved.active||null);
  const [exports,setExports]=useState(saved.exports||{}),[dialog,setDialog]=useState(null);
  const drafts=useRef(saved.drafts||{}),snapshot=useRef(null),cumulativeSession=useRef(saved.cumulative||{});
  const [history,setHistory]=useState(!!initialCandidateId||saved.history||false);
  const mergeRequest=useIncomingMergeIntent({intent:initialMergeIntent,claim:onClaimMergeIntent,projectId,protocolId,queue,onOpen:intent=>{setActive(intent.kind==='merge_source'?intent.candidate_revision_uuid:null);setHistory(intent.kind==='merge_source');}});
  const items=cumulative?queue.data.candidates.filter(item=>!['accepted','covered'].includes(item.status)||item.pending_epoch_count>0):activeProtocolSuggestions({suggestions}).filter(item=>item.protocol_uuid===protocolId);
  const worklist=cumulative?items.filter(item=>selected.includes(reviewKey(item))):reviewWorklist({suggestions:items},selected);
  const current=items.find(item=>item.candidate_revision_uuid===active)||(cumulative&&active?{candidate_revision_uuid:active,protocol_uuid:protocolId}:null);
  snapshot.current={selected,active,exports,drafts:drafts.current,history,cumulative:cumulativeSession.current};
  useEffect(()=>{onSession?.(snapshot.current);},[selected,active,exports,history,onSession]);
  const remember=useCallback(value=>{drafts.current={...drafts.current,[active]:value};onSession?.({...snapshot.current,drafts:drafts.current});},[active,onSession]);
  function rememberCumulative(value){cumulativeSession.current=value;onSession?.({...snapshot.current,cumulative:value});}
  function toggle(item){const key=reviewKey(item);setSelected(previous=>previous.includes(key)?previous.filter(id=>id!==key):[...previous,key]);}
  function startExport(item,accept){const key=reviewKey(item);if(exports[key]?.exported||exports[key]?.phase==='rejected')setExports(previous=>({...previous,[key]:nextWorkbenchWorkflow(previous[key])}));setDialog({key,item,accept});}
  const next=worklist.find(item=>item.candidate_revision_uuid!==active);
  const target=dialog&&(dialog.item||items.find(item=>reviewKey(item)===dialog.key));
  return <div className="incoming-workbench">
    {mergeRequest.pending&&<p role="status">Preparing your merge preview… <button onClick={()=>mergeRequest.finish()}>Cancel merge request</button></p>}
    {mergeRequest.message&&<p role="status">{mergeRequest.message}</p>}
    {(!preparedSupported||history)&&!active&&<header className="incoming-heading"><div className="incoming-heading-title"><span className="incoming-branch-icon"><GitBranch size={19} aria-hidden="true"/></span><h1>{history?'Proposal history':'Incoming proposals'}</h1><span className="incoming-heading-caption">Incoming branch</span></div><div className="incoming-heading-tools"><details className="incoming-review-details incoming-about"><summary><Info size={14} aria-hidden="true"/> About review</summary><div>{cumulative?<p>Queue totals count distinct pending cells and epochs once across saved proposals. Proposal histories may overlap; do not add their counts together. {preparedSupported?'Review opens only unmerged recordings.':'Review opens one frozen proposal; cumulative browsing is unavailable in this build.'}</p>:<p>This queue shows the latest saved proposal for this protocol. Earlier unmerged updates and durable review decisions require the cumulative review service. Viewer selections are session state.</p>}<p>Closing review leaves incoming recordings pending. Merge to main adds eligible incoming epochs while preserving existing main recordings.</p></div></details><button className="incoming-refresh" disabled={loading||queue.loading} onClick={()=>{queue.reload();onRetry?.();}}><RefreshCw size={14} aria-hidden="true"/> Refresh</button></div></header>}
    {cumulative&&(!preparedSupported||history)&&!active&&<div className="incoming-bar-metrics incoming-history-metrics" aria-label="Distinct pending incoming recordings"><span><Layers3 size={17} aria-hidden="true"/><strong>{queue.data.pending_cell_count==null?'—':number(queue.data.pending_cell_count)}</strong><small>{queue.data.pending_cell_count==null?'Cells unavailable':'cells'}</small></span><span><Activity size={17} aria-hidden="true"/><strong>{queue.data.pending_epoch_count==null?'—':number(queue.data.pending_epoch_count)}</strong><small>{queue.data.pending_epoch_count==null?'Epochs unavailable':'incoming epochs'}</small></span></div>}
    {queue.error&&<p className="incoming-contract-note" role="status">Cumulative queue unavailable: {queue.error}. {cumulative?'The previous queue receipt remains visible; refresh before continuing.':'Showing the current legacy proposal only.'}</p>}
    {error&&<div className="error" role="alert">{error}<button onClick={onRetry}>Retry</button></div>}
    {(loading||queue.loading)&&<p role="status">Loading current proposals…</p>}
    {!cumulative&&dialog&&target&&<IncomingExportDialog key={dialog.key} item={target} state={exports[dialog.key]} onState={value=>setExports(previous=>({...previous,[dialog.key]:value}))} onClose={()=>setDialog(null)} onChanged={onChange}/>}
    {cumulative&&queue.data.capabilities.incoming_export&&dialog&&target&&<WorkbenchExportDialog key={dialog.key} protocolId={protocolId} item={target} accept={dialog.accept} state={exports[dialog.key]} onState={value=>setExports(previous=>({...previous,[dialog.key]:{...value,item:target}}))} onClose={()=>setDialog(null)} onChanged={onChange}/>}
    {cumulative&&Object.entries(exports).filter(([,state])=>state.receipt||state.acceptOperation||state.prepared||state.exported).map(([key,state])=><p key={key} role="status">{state.exported?<><a href={state.exported.download_url} download>{state.exported.name||'Download incoming export'}</a> · {number(state.exported.epoch_count)} new epochs</>:<>Saved incoming operation · {state.receipt?'acceptance confirmed; export pending':state.acceptOperation?'acceptance needs receipt recovery':'export needs receipt recovery'} <button disabled={!queue.data.capabilities.incoming_export} onClick={()=>setDialog({key,item:state.item,accept:!!state.receipt||!!state.acceptOperation})}>Resume export</button></>}</p>)}
    {cumulative&&Object.values(exports).flatMap(state=>state.completed||[]).filter(value=>value.exported).map(value=><p key={value.exported.dataset_uuid}><a href={value.exported.download_url} download>{value.exported.name||'Download earlier incoming export'}</a> · {number(value.exported.epoch_count)} new epochs</p>)}
    {preparedSupported&&!history?<CumulativeIncomingReview onReviewProposal={id=>{mergeRequest.finish();setActive(id);setHistory(true);}} toolbarTarget={toolbarTarget} mergeRequest={mergeRequest.pending} onMergeRequestHandled={mergeRequest.finish} filterTarget={filterTarget} onRefresh={()=>{queue.reload();onRetry?.();}} refreshing={loading||queue.loading} queue={queue} protocolId={protocolId} projectId={projectId} revision={revision} onChange={onChange} onQC={onQC} onDefer={()=>setHistory(true)} onHistory={()=>setHistory(true)} session={cumulativeSession.current} onSession={rememberCumulative}/>:<>
    {preparedSupported&&!active&&<button onClick={()=>{setActive(null);setHistory(false);}}>Return to cumulative incoming review</button>}
    {!active?<>
      {!!worklist.length&&<div className="incoming-worklist"><span>{worklist.length} selected proposals · each reviewed independently</span><button onClick={()=>setActive(worklist[0].candidate_revision_uuid)}>Review selected</button></div>}
      {!items.length&&!loading&&!queue.loading&&!error&&<p>No current incoming proposals need review.</p>}
      {items.map(item=>{const key=reviewKey(item),counts=item.diff_counts||{},state=exports[key],recovering=!!(state?.acceptOperation||state?.prepared)&&!state?.exported;return <section className="incoming-proposal" key={key} aria-label={`Incoming update for ${humanize(item.protocol_name)}`}>
        <header><label><input type="checkbox" checked={selected.includes(key)} onChange={()=>toggle(item)}/> {humanize(item.protocol_name)}</label><strong>{item.status==='stale'?'Refresh required':item.deferred||item.status==='deferred'?'Deferred':item.status==='accepted'?'Accepted':item.status==='covered'?'Already in main':item.status==='conflict'?'Conflict requires review':item.status==='source_blocked'?'Source unavailable':'Pending review'}</strong></header>
        <p>{item.source_filename||'Imported recording'} · {time(item.created_at)}</p>
        {cumulative&&<p className="incoming-proposal-pending">{item.pending_epoch_count==null?'Pending epoch count unavailable':`${number(item.pending_epoch_count)} unmerged epochs`}</p>}
        <div className="incoming-counts"><span>+{number(counts.added)} epochs</span><span>−{number(counts.removed)} epochs</span><span>{number(counts.changed)} metadata changes</span></div>
        <div className="incoming-actions"><button className="primary" disabled={recovering||(cumulative?!queue.data.capabilities.incoming_export:item.status!=='pending')} onClick={()=>cumulative?startExport(item,false):setDialog({key,item,accept:false})}>Export</button><button disabled={recovering||!cumulative||!queue.data.capabilities.incoming_export||!queue.data.capabilities.additive_accept} onClick={()=>startExport(item,true)}>Merge & export</button><button disabled={recovering} onClick={()=>setActive(item.candidate_revision_uuid)}>Review first</button></div>
        <details className="incoming-review-details"><summary>Proposal details</summary><div><p>Base <code>{item.baseline_revision_uuid}</code> · proposal <code>{item.candidate_revision_uuid}</code></p>{cumulative&&<p>Proposal counts may overlap; the queue total counts each pending epoch once.</p>}<p className="incoming-contract-note">{cumulative?queue.data.capabilities.incoming_export?'Export new additions independently, or add them to main and export in separate receipt-backed steps. Review first provides fine-grained selection.':'Review the frozen incoming cohort to save selections and preview additions to main. Incoming-only export is awaiting its versioned service.':'Export uses the full saved candidate. Add selected incoming epochs to main and accept all require the additive review service. The existing full-proposal update is a replacement operation.'}</p></div></details>
        {state?.exported&&<p role="status">Export saved: <a href={state.exported.download_url} download>{state.exported.name||'Download artifact'}</a></p>}
      </section>;})}
      {cumulative&&queue.data.next_cursor&&<button disabled={queue.loading} onClick={queue.more}>Load more proposals</button>}
    </>:queue.loading&&!queue.data?<p role="status">Loading the review service before opening this proposal…</p>:current?(cumulative?<FrozenIncomingReview mergeRequest={mergeRequest.pending} onMergeRequestHandled={mergeRequest.finish} onHistory={()=>{mergeRequest.finish();setActive(null);}} toolbarTarget={toolbarTarget} filterTarget={filterTarget} exportIntent={initialExportIntent} acceptOperation={initialAcceptOperation} capabilities={queue.data.capabilities} key={active} projectId={projectId} protocolId={protocolId} item={current} revision={revision} onChange={onChange} onQC={onQC} onDefer={()=>{mergeRequest.finish();setActive(null);}} onNext={next?()=>{mergeRequest.finish();setActive(next.candidate_revision_uuid);}:null} session={drafts.current[active]} onSession={remember}/>:<MetadataExplorer key={active} projectId={projectId} undoScopeId={`incoming:${active}`} protocols={protocols} revision={revision} initialRevisionId={active} initialProtocolId={protocolId} incomingReview={current} onDefer={()=>{mergeRequest.finish();setActive(null);}} onNext={next?()=>{mergeRequest.finish();setActive(next.candidate_revision_uuid);}:null} session={drafts.current[active]} onSession={remember} onChange={onChange} onProtocolApplied={onApplied} onQC={onQC} onInspect={onInspect} onExit={()=>setActive(null)}/>):<div role="status"><p>This proposal is no longer in the current pending queue. Its saved revision remains in candidate history. Refresh the queue to check the current binding.</p><button onClick={()=>setActive(null)}>Back to queue</button></div>}
    </>}
  </div>;
}
