import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {mkdir,writeFile} from 'node:fs/promises';
const work=fileURLToPath(new URL('../../',import.meta.url)).replace(/\/$/,'');
const require=createRequire(work+'/workspace-app/package.json');
const {createServer,transformWithOxc}=await import(pathToFileURL(require.resolve('vite')));
const {default:react}=await import(pathToFileURL(require.resolve('@vitejs/plugin-react')));
const {chromium}=await import('/Users/maxwellsdm/Documents/GitHub/epicTreeGUI/desktop/node_modules/playwright/index.mjs');
const output=process.env.SCOPED_QA_OUTPUT||'/tmp/rieke-scoped-predicate-browser';await mkdir(output,{recursive:true});
const entry=`import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import '/src/styles.css';import '/src/components/Inspector.css';import ProtocolViewFilter from '/src/components/ProtocolViewFilter.jsx';
function App(){const [candidate,setCandidate]=useState(false),[filters,setFilters]=useState({metadata_predicate:JSON.stringify({field:'parameters/example',operator:'eq',value:0})});window.switchCandidate=()=>setCandidate(true);return <main style={{padding:24}}><h1>Scoped predicate fixture</h1><p>Isolated mocked frozen cohort · no live database</p><ProtocolViewFilter protocol={{definition:{protocol_uuid:'p',project_uuid:'project',name:'Pinned fixture',query:{all:[]}},counts:{epochs:2},cells:[]}} projectId="project" filters={filters} revision={0} onChange={next=>{window.applied=next;setFilters(next);}} readContext={candidate?{root:'/protocols/p/workbench/candidates/r',candidate_scope_revision:'fixture-scope'}:null}/><pre>{JSON.stringify(filters)}</pre></main>};createRoot(document.getElementById('root')).render(<App/>);`;
const plugin={name:'scoped-browser-fixture',resolveId(id){if(id==='virtual:scoped-entry')return '\0virtual:scoped-entry.jsx';},load(id){if(id==='\0virtual:scoped-entry.jsx')return entry;},transform(code,id){if(id==='\0virtual:scoped-entry.jsx')return transformWithOxc(code,'scoped-fixture.jsx',{lang:'jsx',jsx:{runtime:'automatic'}});},configureServer(server){server.middlewares.use('/scoped-check.html',async(req,res)=>{res.setHeader('Content-Type','text/html');res.end(await server.transformIndexHtml('/scoped-check.html','<html><body><div id="root"></div><script type="module" src="/@id/__x00__virtual:scoped-entry.jsx"></script></body></html>'));});}};
let server,browser;const requests=[],errors=[];
try{
 server=await createServer({root:work+'/workspace-app',configFile:false,plugins:[plugin,react()],server:{host:'127.0.0.1',port:Number(process.env.SCOPED_QA_PORT||5196),strictPort:true,hmr:false,ws:false},logLevel:'error'});await server.listen();
 browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const page=await browser.newPage({viewport:{width:1280,height:900}});page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/api/**',async route=>{const req=route.request(),url=new URL(req.url());const body=req.postDataJSON();requests.push({path:url.pathname,body});let result={};if(url.pathname.endsWith('/field-registry'))result={fields:[{id:'parameters/example',label:'Example',category:'Parameters',path:'parameters.example',types:['number'],operators:['eq','gt','missing','is_null']}],generation:{metadata:'m',typed:'t',source:'s',publication:'p',annotation:'a'}};else if(url.pathname==='/api/explore/summaries')result={status:'pending',request_id:'fixture-job',generation:{metadata:'m',typed:'t',source:'s',publication:'p',annotation:'a',binding:'b'}};else if(url.pathname==='/api/explore/summaries/fixture-job')result={status:'ready',request_id:'fixture-job',generation:{metadata:'m',typed:'t',source:'s',publication:'p',annotation:'a',binding:'b'},result:{matched_count:0,summaries:{}}};else if(url.pathname.endsWith('/summary'))result={...body,counts:{epochs:1}};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(result)});});
 await page.goto(`http://127.0.0.1:${process.env.SCOPED_QA_PORT||5196}/scoped-check.html`);await page.getByRole('button',{name:'Filter view',exact:true}).click();await page.getByRole('button',{name:'Metadata conditions…',exact:true}).click();await page.getByRole('dialog').waitFor();
 await page.getByRole('button',{name:'Preview matches',exact:true}).click();await page.getByText('0 matching epochs',{exact:true}).waitFor();await page.screenshot({path:output+'/protocol-editor.png'});
 await page.getByRole('button',{name:'Apply view criteria',exact:true}).click();assert.ok((await page.evaluate(()=>window.applied)).metadata_predicate);
 await page.evaluate(()=>window.switchCandidate());await page.getByRole('button',{name:'Filter view',exact:true}).click();await page.getByRole('button',{name:'Metadata conditions…',exact:true}).click();await page.getByRole('button',{name:'Preview matches',exact:true}).click();await page.getByText('1 matching epochs',{exact:true}).waitFor();await page.screenshot({path:output+'/candidate-editor.png'});
 assert.equal(requests.some(item=>item.path==='/api/explore/run'),false);const counts=requests.filter(item=>item.path==='/api/explore/summaries');assert.ok(counts.length);assert.ok(counts.every(item=>item.body.protocol_uuid==='p'));assert.ok(counts.some(item=>item.body.summary_fields.length===0));assert.ok(requests.find(item=>item.path.endsWith('/candidates/r/summary')).body.candidate_scope_revision==='fixture-scope');assert.deepEqual(errors,[]);
 await writeFile(output+'/receipt.json',JSON.stringify({fixture_only:true,port:5196,checks:['restored single condition renders shared editor','protocol scoped count-only preview','zero count distinct from unavailable','explicit apply preserves metadata AST','candidate preview stays on frozen root','no global run','no browser exceptions'],requests,errors},null,2));console.log(output);
}finally{await browser?.close();await server?.close();}
