import test from 'node:test';import assert from 'node:assert/strict';
import {createStartupRestore} from './project-workspace/startupRestore.js';
const saved={projectPath:'/owned/a',projectId:'uuid'},project={path:'/owned/a',uuid:'uuid',name:'Owned',available:true};
const tick=()=>new Promise(r=>setImmediate(r));
function setup(overrides={}){let calls=[],states=[],finish=[],cancelled=false;const options={inventory:{projects:[project]},bridge:{startupSession:async()=>saved,chooseStartup:async()=>{cancelled=true;},cancelStartup:async()=>{cancelled=true;},openStartup:async()=>{finish.push(true);return {restored:!cancelled,closed:cancelled};}},request:async route=>{calls.push(route);return route.endsWith('inspect-folder')?{valid:true,kind:'project',project}: {url:'http://127.0.0.1:12345'};},onState:s=>states.push(s),...overrides};return {control:createStartupRestore(options),options,calls,states,finish};}
test('saved exact project is inspected before open; current authority stays in main',async()=>{const h=setup();await h.control.start();assert.deepEqual(h.calls,['/projects/inspect-folder']);assert.equal(h.finish.length,1);});
test('missing, moved, replaced or unavailable project never opens',async()=>{for(const p of [[],[{...project,path:'/copy'}],[{...project,uuid:'other'}],[{...project,available:false}]]){const h=setup({inventory:{projects:p}});await h.control.start();assert.equal(h.calls.length,0);assert.ok(h.states.some(s=>s.error));}});
test('inspection identity change and incompatible project block opening',async()=>{for(const report of [{valid:true,kind:'project',project:{...project,uuid:'other'}},{valid:true,kind:'project',project,desktop_compatibility:{requires_migration:true}},{valid:false}]){const h=setup({request:async route=>{assert.ok(route.endsWith('inspect-folder'));return report;}});await h.control.start();assert.equal(h.finish.length,0);assert.ok(h.states.some(s=>s.error));}});
test('cancel during spawned startup leaves graceful completion owned by main',async()=>{let release;const h=setup();h.options.bridge.openStartup=()=>new Promise(r=>{release=r;});const pending=h.control.start();await tick();await h.control.cancel();release({restored:false,closed:true});await pending;assert.ok(!h.states.some(s=>s.phase==='complete'));});
test('newer choice before saved state resolves wins; no service opens',async()=>{let release;const h=setup();h.options.bridge.startupSession=()=>new Promise(r=>{release=r;});const pending=h.control.start();await tick();h.control.supersede();release(saved);await pending;assert.equal(h.calls.length,0);});
test('cleanup errors remain visible and no successful restore is published',async()=>{const h=setup();h.options.bridge.openStartup=async()=>{throw Error('cleanup requires recovery');};await h.control.start();assert.ok(h.states.some(s=>s.error==='cleanup requires recovery'));assert.ok(!h.states.some(s=>s.phase==='complete'));});
