'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {execFile}=require('node:child_process'),{promisify}=require('node:util'),{createHash}=require('node:crypto');
const run=promisify(execFile),{_electron}=require('/Users/maxwellsdm/Documents/Codex/2026-10-03/task-4/Rieke-OS-benchmark-integration/desktop/node_modules/playwright');
const {startSampler}=require('./diagnose_lazy_sampler.cjs');
const root=__dirname,home=path.join(root,'home'),bundle=path.join(home,'Applications/Disco.app'),executable=path.join(bundle,'Contents/MacOS/Disco');
const runId=process.env.DISCO_RUN_ID||'smoke-1',evidence=path.join(root,'evidence',runId);
const output=path.join(evidence,'comparison.json'),delay=ms=>new Promise(r=>setTimeout(r,ms));
const receipt={format:'isolated-lazy-root-diagnostic',started_at:new Date().toISOString(),passed:false,variants:[],limits:['Counterbalanced samples are small-sample diagnostic; OS cache uncontrolled; no release budget qualification.','Same clone; distinct fresh profiles and synthetic projects; first synthetic import + 127 analytic trace samples.','CPU/RSS are sampled owned-process observations, not exact peak or all exited short-lived processes.','Structural window timestamp is Playwright first-window availability, not first paint.']};
let app,page,current,userdata,cap,origin,stopSampling=null;
const write=()=>fs.writeFile(output,JSON.stringify(receipt,null,2)+'\n');
async function processes(){let {stdout}=await run('/bin/ps',['-ww','-axo','pid=,ppid=,time=,rss=,comm='],{timeout:5000,maxBuffer:2097152});return stdout.split('\n').flatMap(l=>{let m=/^\s*(\d+)\s+(\d+)\s+(\S+)\s+(\d+)\s+(.+)$/.exec(l);return m&&m[5].startsWith(bundle+'/')?[{pid:+m[1],ppid:+m[2],cpu_time:m[3],rss_kib:+m[4],executable:m[5]}]:[]});}
async function mark(name,more={}){current.events.push({name,elapsed_ms:performance.now()-current.t0,wall:new Date().toISOString(),...more});await write();}
async function api(route,body,at=origin){let r=await fetch(at+route,{method:body===undefined?'GET':'POST',headers:{'X-Rieke-Desktop-Capability':cap,'X-Workspace-Request':'1','Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(90000)});let v=await r.json();assert.ok(r.ok,route+' HTTP '+r.status+' '+JSON.stringify(v).slice(0,250));return v;}
async function identity(){let r=JSON.parse(await fs.readFile(path.join(userdata,'desktop-service.json')));assert.ok(r.executable.startsWith(bundle+'/'));let result=await run('/bin/ps',['eww','-p',String(r.pid),'-o','command=']);cap=result.stdout.match(/(?:^|\s)RIEKE_DESKTOP_CAPABILITY=([a-f0-9]{64})(?:\s|$)/)?.[1];assert.ok(cap);origin='http://127.0.0.1:'+r.port;let h=await api('/api/desktop/health');assert.equal(h.pid,r.pid);assert.equal(h.ready,true);current.root_pid=r.pid;}
async function author(){let d=page.getByRole('dialog',{name:'Tag author',exact:true});if(await d.waitFor({state:'visible',timeout:2000}).then(()=>true,()=>false)){await d.getByRole('textbox').fill('Owned lifecycle diagnostic');await d.getByRole('button',{name:'Create profile',exact:true}).click();await d.waitFor({state:'hidden'});}}
async function openProject(index){await mark('project'+index+'.request');let project=(await api('/api/projects',{name:'Owned '+current.mode+' '+index,project_directory:path.join(home,'projects-'+runId+'-'+current.sample_name,'p'+index)})).project;await page.reload();await mark('project'+index+'.selected');if(index===1){await page.getByRole('button',{name:new RegExp('^Open Owned '+current.mode+' '+index+',')}).click()}else{await page.getByRole('navigation',{name:'Research projects'}).getByRole('button',{name:'Owned '+current.mode+' '+index,exact:true}).click()}await page.waitForURL(url=>url.origin!==origin&&url.origin!==(current.previous_origin||''),{timeout:90000});let at=new URL(page.url()).origin;current.previous_origin=at;let auth=await api('/api/desktop/authorize-project',{port:+new URL(at).port});assert.equal(auth.health.project_uuid,project.uuid);assert.equal(auth.health.project_path,await fs.realpath(project.path));assert.equal(auth.record.bound,true);await mark('project'+index+'.backend_ready');await page.getByRole('button',{name:'Project overview',exact:true}).waitFor({timeout:60000});await author();await page.getByRole('button',{name:'Project overview',exact:true}).click();let overview=await api('/api/overview',undefined,at);assert.equal(overview.counts.epochs,0);assert.equal(overview.project.project_uuid,project.uuid);let inventory=await api('/api/projects',undefined,at);assert.equal(inventory.current_project_uuid,project.uuid);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await mark('project'+index+'.authoritative_interaction');let native=JSON.parse(await fs.readFile(path.join(project.path,'database/native-runtime.json')));current.projects.push({uuid:project.uuid,path:project.path,pid:auth.record.pid,socket:native.socket});return at;}
async function scientific(at){await mark('science.import.request');let job=await api('/api/imports',{source_path:path.join(root,'synthetic/synthetic-navigation.h5')},at),deadline=Date.now()+90000;while(true){let jobs=(await api('/api/jobs',undefined,at)).jobs;let j=jobs.find(x=>x.job_uuid===job.job_uuid);if(['complete','complete_with_warnings','failed','interrupted','duplicate'].includes(j.status)){assert.ok(['complete','complete_with_warnings'].includes(j.status),j.status);break}assert.ok(Date.now()<deadline,'import deadline');await delay(250)}let overview=await api('/api/overview',undefined,at);assert.equal(overview.counts.epochs,129);assert.equal(overview.counts.cells,3);const truth=JSON.parse(await fs.readFile(path.join(root,'synthetic/truth.json'))),row=truth.rows[0];let trace=await api('/api/epochs/'+row.epoch_uuid+'/trace?stream_uuid='+row.stream_uuid+'&start=17&count=127',undefined,at);assert.equal(trace.sample_rate,row.sample_rate);assert.equal(trace.units,row.units);assert.equal(trace.epoch_uuid,row.epoch_uuid);assert.equal(trace.stream_uuid,row.stream_uuid);assert.deepEqual(trace.values,Array.from({length:127},(_,i)=>row.formula.offset+(17+i)*row.formula.sample_coefficient));await mark('science.first_authoritative_result',{cells:3,epochs:129,exact_trace_samples:127,exact_epoch_stream_ids:true});await page.reload();await page.getByRole('button',{name:'Project overview',exact:true}).waitFor();await page.getByRole('button',{name:'Project overview',exact:true}).click();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await mark('science.renderer_refresh');}
async function quit(){await mark('quit.request');let child=app.process(),exit=child.exitCode!==null?Promise.resolve(child.exitCode):new Promise(r=>child.once('exit',r));await app.evaluate(({app})=>app.quit());let code=await Promise.race([exit,delay(45000).then(()=>{throw Error('orderly quit timeout')})]);assert.equal(code,0);let left;let deadline=Date.now()+10000;do{left=await processes();if(!left.length)break;await delay(200)}while(Date.now()<deadline);assert.equal(left.length,0);for(const project of current.projects){assert.equal(JSON.parse(await fs.readFile(path.join(project.path,'database/native-owner.json'))).clean_shutdown,true);assert.equal(await fs.stat(project.socket).then(()=>true,()=>false),false);assert.equal(await fs.stat(path.join(project.path,'database/native-runtime.json')).then(()=>true,()=>false),false)}await mark('quit.zero_owned_processes',{owned_sockets_absent:true,native_clean_shutdown:true});app=null;page=null;current.zero_owned=true;}
async function variant(mode,index){assert.ok(['baseline','lazy'].includes(mode));const sampleName=index+'-'+mode;assert.equal((await processes()).length,0);current={mode,sample_name:sampleName,t0:performance.now(),events:[],resources:[],sampling_errors:[],projects:[],passed:false};receipt.variants.push(current);userdata=path.join(home,'state-'+runId+'-'+sampleName);let phaseDir=path.join(evidence,'phases-'+sampleName);await fs.mkdir(phaseDir,{recursive:true});await fs.mkdir(path.join(home,'projects-'+runId+'-'+sampleName),{recursive:true});const sampled=current;stopSampling=startSampler(async()=>{try{sampled.resources.push({elapsed_ms:performance.now()-sampled.t0,processes:await processes()});}catch(e){sampled.sampling_errors.push(e.message)}});await mark('launch.request');app=await _electron.launch({executablePath:executable,args:['--user-data-dir='+userdata],env:{...process.env,HOME:home,TMPDIR:root,XDG_CONFIG_HOME:userdata,DISCO_LIFECYCLE_DIAGNOSTIC_DIR:phaseDir,DISCO_LAZY_ROOT_EXPERIMENT:mode==='lazy'?'1':'0'},chromiumSandbox:true,bypassCSP:false,timeout:60000});page=await app.firstWindow({timeout:60000});await mark('window.available');while(!await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().some(w=>w.isVisible()))){await delay(50)}await mark('window.visible');let actual=await app.evaluate(({app})=>({home:process.env.HOME,userdata:app.getPath('userData'),path:app.getAppPath(),electron:process.versions.electron}));assert.equal(actual.home,home);assert.equal(actual.userdata,userdata);assert.ok(actual.path.startsWith(bundle+'/'));current.runtime=actual;page.setDefaultTimeout(20000);page.on('pageerror',e=>current.renderer_errors=(current.renderer_errors||[]).concat(e.message));await page.getByRole('heading',{name:'Your projects',exact:true}).waitFor({timeout:60000});assert.ok(await page.getByRole('button',{name:/^Create a new project/}).isEnabled());let inventory=await page.evaluate(()=>fetch('/api/projects').then(r=>r.json()));assert.equal(inventory.launcher,true);await identity();await mark('root.usable');let at=await openProject(1);await scientific(at);await openProject(2);let health=await api('/api/desktop/health');assert.equal(health.services.length,2);assert.equal(new Set(health.services.map(x=>x.pid)).size,2);assert.equal((await api('/api/overview',undefined,at)).counts.epochs,129);await quit();if(stopSampling){await stopSampling();stopSampling=null;}assert.equal((current.renderer_errors||[]).length,0);current.passed=true;await write();console.log('PASS '+mode);}
(async()=>{await fs.mkdir(path.dirname(output),{recursive:true});const digest=async p=>createHash('sha256').update(await fs.readFile(p)).digest('hex');receipt.asar_sha256=await digest(path.join(bundle,'Contents/Resources/app.asar'));receipt.manifest_sha256=await digest(path.join(bundle,'Contents/Resources/runtime/runtime-manifest.json'));for(const [index,mode] of (process.env.DISCO_VARIANTS||'baseline').split(',').entries())await variant(mode,index);receipt.passed=true})().catch(async e=>{receipt.error=e.stack;console.error(e.message);if(app&&page){try{await quit();receipt.failure_cleanup='orderly quit'}catch(c){receipt.cleanup_error=c.message}}process.exitCode=1}).finally(async()=>{if(stopSampling){await stopSampling();stopSampling=null;}receipt.ended_at=new Date().toISOString();receipt.final_owned_processes=await processes();await write();console.log('END '+receipt.ended_at+' zero='+!receipt.final_owned_processes.length);process.exit(process.exitCode||0)});
setTimeout(()=>{console.error('Controller deadline; owned fixture retained for explicit cleanup');process.exit(2)},420000).unref();
